##Import Section for Libraries

In [ ]:
import csv
import pickle
import shutil
from pathlib import Path
import logging
import json
import re
import argparse
import time
import math
from datetime import datetime
import collections
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
from sklearn import datasets, model_selection, metrics
import tensorflow as tf
import torch
import xgboost as xgb
import lightgbm as lgb


Implement Python code in a Google Colab or Jupyter notebook to demonstrate the usage of basic libraries including Statistics, Math, Numpy, and Scipy. Specifically, show examples of: a) Math functions like floor(), ceil(), sqrt(), isqrt(), and gcd(). b) Numpy array attributes (ndim, shape, size) and methods (sum(), mean(), sort(), sin()). c) Scipy methods like det() and eig(). d) Reshaping a 1D list into 2D and 3D matrices using Numpy. e) Generating random arrays and matrices using Numpy. f) Finding the determinant of a matrix using Scipy. g) Finding eigenvalues and eigenvectors of a matrix using Scipy.

## Implement `math` library functions

usage of `floor()`, `ceil()`, `sqrt()`, `isqrt()`, and `gcd()` from the `math` module.


In [ ]:
import math

float_num = 10.7
floor_result = math.floor(float_num)
print(f"The floor of {float_num} is: {floor_result}")

ceil_result = math.ceil(float_num)
print(f"The ceiling of {float_num} is: {ceil_result}")

num_to_sqrt = 25.1
sqrt_result = math.sqrt(num_to_sqrt)
print(f"The square root of {num_to_sqrt} is: {sqrt_result}")

non_negative_int = 17
isqrt_result = math.isqrt(non_negative_int)
print(f"The integer square root of {non_negative_int} is: {isqrt_result}")

num1 = 48
num2 = 18
gcd_result = math.gcd(num1, num2, 172 , 1000)
print(f"The greatest common divisor of {num1} and {num2} is: {gcd_result}")

num3 = 12
try:
    gcd_multiple_result = math.gcd(num1, num2, num3)
    print(f"The greatest common divisor of {num1}, {num2}, and {num3} is: {gcd_multiple_result}")
except TypeError:
    print("math.gcd() with multiple arguments requires Python 3.9 or later.")
    chained_gcd = math.gcd(num1, math.gcd(num2, num3))
    print(f"Using chained gcd: The greatest common divisor of {num1}, {num2}, and {num3} is: {chained_gcd}")


The floor of 10.7 is: 10
The ceiling of 10.7 is: 11
The square root of 25.1 is: 5.0099900199501395
The integer square root of 17 is: 4
The greatest common divisor of 48 and 18 is: 2
The greatest common divisor of 48, 18, and 12 is: 6


## Implement `numpy` array attributes and methods

Create a numpy array and demonstrate the usage of attributes like `ndim`, `shape`, `size`, and methods like `sum()`, `mean()`, `sort()`, and `sin()`.


In [ ]:
import numpy as np

numpy_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f"Array ndim: {numpy_array.ndim}")
print(f"Array shape: {numpy_array.shape}")
print(f"Array size: {numpy_array.size}")

print(f"Array sum: {numpy_array.sum()}")
print(f"Array mean: {numpy_array.mean()}")

print(f"Array sorted (flattened): {np.sort(numpy_array, axis=0)}")
sin_array = np.sin(numpy_array)
print(f"Array after applying sin():\n{sin_array}")

Array ndim: 2
Array shape: (3, 3)
Array size: 9
Array sum: 45
Array mean: 5.0
Array sorted (flattened): [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after applying sin():
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


## Reshape a list into a numpy array

Convert a 1D Python list into a 2D and 3D numpy array using reshape.


In [ ]:
import numpy as np

my_list = list(range(24))
numpy_1d_array = np.array(my_list)

numpy_2d_array = numpy_1d_array.reshape((4, 6))
print("2D Reshaped Array:")
display(numpy_2d_array)

numpy_3d_array = numpy_1d_array.reshape((2, 3, 4))
print("\n3D Reshaped Array:")
display(numpy_3d_array)

2D Reshaped Array:


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])


3D Reshaped Array:


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## Generate random arrays and matrices using `numpy`

Create random 1D arrays and 2D matrices using numpy's random functions.


In [ ]:
random_1d_array = np.random.rand(10)

random_2d_matrix = np.random.randint(1, 101, size=(3, 4))

print("Random 1D Array:")
display(random_1d_array)

print("\nRandom 2D Matrix:")
display(random_2d_matrix)

Random 1D Array:


array([0.06447443, 0.08226468, 0.38263783, 0.09601458, 0.59293055,
       0.60612896, 0.52475498, 0.14294375, 0.84562095, 0.72461715])


Random 2D Matrix:


array([[39, 95, 61, 44],
       [76, 62, 79, 33],
       [86, 14, 32, 17]])

## Find the determinant of a matrix using `scipy`

Use `scipy.linalg.det()` to calculate the determinant of a matrix.


In [ ]:
from scipy.linalg import det
import numpy as np

matrix_to_det = np.array([[2, 1], [4, 3]])

determinant_result = det(matrix_to_det)

print(f"The determinant of the matrix is: {determinant_result}")

The determinant of the matrix is: 2.0


## Find eigenvalues and eigenvectors of a matrix using `scipy`

Use `scipy.linalg.eig()` to find the eigenvalues and eigenvectors of a matrix.


In [ ]:
from scipy.linalg import eig
import numpy as np

matrix_for_eig = np.array([[3, 2], [1, 4]])

eigenvalues, eigenvectors = eig(matrix_for_eig)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[2.+0.j 5.+0.j]

Eigenvectors:
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]



##Implement the following using Python libraries:
1. Create a pandas Series and display it.
2. Access the index and values of the Series.
3. Compare a NumPy array with a pandas Series.
4. Define a pandas Series with individual indices.
5. Access a single value of a pandas Series.
6. Load a dataset into a pandas DataFrame.

## Create a series using pandas and display

Create a simple pandas Series and display its content.


In [ ]:
import pandas as pd

my_series = pd.Series([10, 20, 30, 40, 50])

display(my_series)

0    10
1    20
2    30
3    40
4    50
dtype: int64

## Access the index and the values of a series

Demonstrate how to access the index and the values separately from the created Series.


In [ ]:
series_index = my_series.index

series_values = my_series.values

print("Series Index:")
display(series_index)

print("\nSeries Values:")
display(series_values)

Series Index:


RangeIndex(start=0, stop=5, step=1)


Series Values:


array([10, 20, 30, 40, 50])

## Compare an array using numpy with a series using pandas

Briefly explain the key differences between a NumPy array and a pandas Series and show a simple example of each.


In [ ]:
import numpy as np
import pandas as pd

numpy_array_example = np.array([1, 2, 3, 4, 5])

pandas_series_example = pd.Series([10, 20, 30, 40, 50])

print("NumPy Array Example:")
display(numpy_array_example)

print("\nPandas Series Example:")
display(pandas_series_example)

NumPy Array Example:


array([1, 2, 3, 4, 5])


Pandas Series Example:


0    10
1    20
2    30
3    40
4    50
dtype: int64

## Define series objects with individual indices

Define a pandas Series with individual indices.


In [ ]:
import pandas as pd

data = {'a': 100, 'b': 200, 'c': 300, 'd': 400}
series_with_custom_index = pd.Series(data)

print("Pandas Series with Custom Indices:")
display(series_with_custom_index)

Pandas Series with Custom Indices:


a    100
b    200
c    300
d    400
dtype: int64

## Access single value of a series

Show different ways to access a single element from a pandas Series using its index.


In [ ]:

value_at_index_0 = my_series[0]
print(f"Value at integer index 0 of my_series: {value_at_index_0}")

value_at_label_b = series_with_custom_index['b']
print(f"Value at label index 'b' of series_with_custom_index: {value_at_label_b}")

Value at integer index 0 of my_series: 10
Value at label index 'b' of series_with_custom_index: 200


## Load datasets in a data frame variable using pandas

Demonstrate how to load a dataset into a pandas DataFrame.


In [ ]:
import pandas as pd


csv_url = 'Ionosphere.csv'
df = pd.read_csv(csv_url)

print("First 5 rows of the loaded DataFrame:")
display(df.head())

First 5 rows of the loaded DataFrame:


V1  V2       V3       V4       V5       V6       V7       V8       V9  \
0   1   0  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000   
1   1   0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
2   1   0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
3   1   0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
4   1   0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   

       V10  ...      V26      V27      V28      V29      V30      V31  \
0  0.03760  ... -0.51171  0.41078 -0.46168  0.21266 -0.34090  0.42267   
1 -0.04549  ... -0.26569 -0.20468 -0.18401 -0.19040 -0.11593 -0.16626   
2  0.01198  ... -0.40220  0.58984 -0.22145  0.43100 -0.17365  0.60436   
3  0.00000  ...  0.90695  0.51613  1.00000  1.00000 -0.20099  0.25682   
4 -0.16399  ... -0.65158  0.13290 -0.53206  0.02431 -0.62197 -0.05707   

       V32      V33      V34  Class  
0 -0.54487  0.18641 -0.45300      1  
1 -0.06288 -0.13738 -0.02447      0  
2 -0.24180  0.56045 -0.38238      1  
3  1.00000 -0.32382  1.00000      0  
4 -0.59573 -0.04608 -0.65697      1  

[5 rows x 35 columns]

from matplotlib import pyplot as plt
_df_24['V3'].plot(kind='hist', bins=20, title='V3')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_25['V4'].plot(kind='hist', bins=20, title='V4')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_26['V5'].plot(kind='hist', bins=20, title='V5')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_27['V6'].plot(kind='hist', bins=20, title='V6')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_28.plot(kind='scatter', x='V3', y='V4', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_29.plot(kind='scatter', x='V4', y='V5', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_30.plot(kind='scatter', x='V5', y='V6', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_31.plot(kind='scatter', x='V6', y='V7', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['V1']
  ys = series['V4']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_32.sort_values('V1', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('V1')
_ = plt.ylabel('V4')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['V1']
  ys = series['V5']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_33.sort_values('V1', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('V1')
_ = plt.ylabel('V5')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['V1']
  ys = series['V6']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_34.sort_values('V1', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('V1')
_ = plt.ylabel('V6')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['V1']
  ys = series['V7']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_35.sort_values('V1', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('V1')
_ = plt.ylabel('V7')

from matplotlib import pyplot as plt
_df_36['V3'].plot(kind='line', figsize=(8, 4), title='V3')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_37['V4'].plot(kind='line', figsize=(8, 4), title='V4')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_38['V5'].plot(kind='line', figsize=(8, 4), title='V5')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_39['V6'].plot(kind='line', figsize=(8, 4), title='V6')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
from sklearn.datasets import load_iris

iris = load_iris()

df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

print("First 5 rows of the loaded DataFrame:")
display(df.head())

First 5 rows of the loaded DataFrame:


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2


## Creation and Loading different types of datasets in Python using the required libraries.
*i. Creation using pandas*  
*ii. Loading CSV dataset files using Pandas*  
*iii. Loading datasets using sklearn*



Create a pandas DataFrame from a dictionary or a list of lists.

In [ ]:
import pandas as pd

data_dict = {'col1': [1, 2, 3], 'col2': [4, 5, 6]}
df_from_dict = pd.DataFrame(data_dict)
print("DataFrame created from a dictionary:")
display(df_from_dict)

data_list = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
df_from_list = pd.DataFrame(data_list, columns=['A', 'B', 'C'])
print("\nDataFrame created from a list of lists:")
display(df_from_list)

DataFrame created from a dictionary:


col1  col2
0     1     4
1     2     5
2     3     6


DataFrame created from a list of lists:


A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


Load a CSV dataset file into a pandas DataFrame.

In [ ]:


print("Displaying the first 5 rows of the DataFrame (previously loaded):")
display(df.head())

Displaying the first 5 rows of the DataFrame (previously loaded):


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2


Load a dataset using scikit-learn's built-in datasets.

In [ ]:
import pandas as pd
from sklearn.datasets import load_wine

wine = load_wine()

df_wine = pd.DataFrame(data=wine.data, columns=wine.feature_names)

df_wine['target'] = wine.target

print("First 5 rows of the Wine dataset loaded from scikit-learn:")
display(df_wine.head())

First 5 rows of the Wine dataset loaded from scikit-learn:


alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0